In [9]:
import pandas as pd
movies=pd.read_csv("/Users/aryanshah/Developer/Thesis/recosys/data/processed/movies_clean.csv")
ratings=pd.read_csv("/Users/aryanshah/Developer/Thesis/recosys/data/processed/ratings_clean.csv")

In [21]:
movies.shape
movies.head()
movies.tail()

,movieId,title,genres,imdbId,tmdbId
87456,292731,The Monroy Affaire (2022),Drama,26812510,1032473
87457,292737,Shelter in Solitude (2023),"Comedy, Drama",14907358,986674
87458,292753,Orca (2023),Drama,12388280,948139
87459,292755,The Angry Breed (1968),Drama,64027,182776
87460,292757,Race to the Summit (2023),"Action, Adventure, Documentary",28995566,1174725

In [19]:
ratings.shape
ratings.head()
ratings.tail()

          userId  movieId  rating
26550146  200948    79702     4.5
26550147  200948    79796     1.0
26550148  200948    80350     0.5
26550149  200948    80463     3.5
26550150  200948    87304     4.5